-- Frozen schema fixture from before accept_policy and inbox.done_seq existed.
-- Keep this independent of collab.py's live SCHEMA so migrations are tested from a
-- genuinely old shape rather than a database generated by today's implementation.
CREATE TABLE projects (
  name TEXT PRIMARY KEY, topic TEXT, goal TEXT,
  state TEXT NOT NULL DEFAULT 'open',
  next_seq INTEGER NOT NULL DEFAULT 1,
  max_rounds INTEGER DEFAULT 6,
  created_at TEXT, updated_at TEXT
);
CREATE TABLE participants (
  project TEXT, agent_id TEXT, role TEXT,
  last_heartbeat TEXT,
  PRIMARY KEY (project, agent_id)
);
CREATE TABLE blobs (
  sha256 TEXT PRIMARY KEY, path TEXT, bytes INTEGER, created_at TEXT
);
CREATE TABLE artifacts (
  project TEXT, name TEXT, version INTEGER,
  sha256 TEXT REFERENCES blobs(sha256),
  created_by TEXT, created_at TEXT,
  PRIMARY KEY (project, name, version)
);
CREATE TABLE messages (
  message_id TEXT PRIMARY KEY,
  idempotency_key TEXT,
  project TEXT, thread_id TEXT, round INTEGER, parent_message_id TEXT,
  seq INTEGER, from_agent TEXT, to_agent TEXT, role TEXT, type TEXT,
  refs_json TEXT, body TEXT, created_at TEXT,
  UNIQUE (project, idempotency_key)
);
CREATE TABLE inbox (
  message_id TEXT, recipient TEXT,
  status TEXT DEFAULT 'pending',
  claimed_by TEXT, claim_token TEXT,
  leased_until TEXT, deliveries INTEGER DEFAULT 0,
  PRIMARY KEY (message_id, recipient)
);
CREATE INDEX idx_inbox ON inbox(recipient, status);
CREATE INDEX idx_msg_seq ON messages(project, seq);

INSERT INTO projects
  (name, topic, goal, state, next_seq, max_rounds, created_at, updated_at)
VALUES
  ('legacy', 'migration', 'preserve data', 'gathering', 2, 6,
   '2025-01-01T00:00:00.000000Z', '2025-01-01T00:00:00.000000Z');
INSERT INTO participants
  (project, agent_id, role, last_heartbeat)
VALUES
  ('legacy', 'codex-1', 'reviewer', '2025-01-01T00:00:00.000000Z');
INSERT INTO messages
  (message_id, idempotency_key, project, thread_id, round, parent_message_id,
   seq, from_agent, to_agent, role, type, refs_json, body, created_at)
VALUES
  ('legacy-message', NULL, 'legacy', 'legacy-message', 1, NULL,
   1, 'claude-1', 'codex-1', 'initiator', 'review_request', '{}',
   'legacy review', '2025-01-01T00:00:00.000000Z');
INSERT INTO inbox
  (message_id, recipient, status, claimed_by, claim_token, leased_until, deliveries)
VALUES
  ('legacy-message', 'codex-1', 'done', NULL, NULL, NULL, 1);
